// chameleon -- a censorship-resistant transport
// Copyright (C) 2026 The chameleon authors
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License version 3 as published by the Free
// Software Foundation.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// this program. If not, see <https://www.gnu.org/licenses/>.

// Package realm implements Hysteria Realms: rendezvous-assisted UDP hole
// punching between a client and a server that are both behind NAT.
//
// # Trust model
//
// The rendezvous server is a meeting point, not an authority. It sees every
// address a peer announces and every byte of the punch metadata it relays, so
// it must be treated as an active attacker that can add, drop, delay or forge
// anything it forwards.
//
// What the rendezvous server can do:
//
//   - Deny service: refuse to relay, delay, or hand out addresses that never
//     answer. Availability is not defended here.
//   - Learn the reflexive addresses of every peer in a realm, and correlate
//     which peers talk to each other and when.
//   - Read and replay the punch metadata (nonce and obfuscation key). Punch
//     packets are obfuscated, not authenticated, so the rendezvous server can
//     mint packets that any peer in the attempt will decode as valid.
//   - Announce addresses that do not belong to the peer, i.e. steer a client
//     at a machine of its choosing, as long as it announces that machine.
//
// What the rendezvous server cannot do:
//
//   - Hand a peer a QUIC address it never announced. Punch only reports a
//     source address that appears in the candidate set derived from the
//     addresses the attempt started with (see PunchSourcePolicy), so packets
//     injected from an unrelated address are dropped instead of becoming the
//     QUIC peer. Candidates are also filtered and capped, which bounds how
//     much punch traffic a malicious realm can aim at a third party.
//   - Impersonate the Hysteria server to a client that pins it. The QUIC
//     handshake that follows the punch verifies the server certificate, which
//     the rendezvous server has no way to influence.
//
// The last point holds only under its precondition, and callers should read it
// as a requirement rather than a guarantee: with a pinned certificate (or an
// SNI the rendezvous server cannot obtain a certificate for) a steered client
// fails the handshake, but a client that verifies against the rendezvous
// hostname with WebPKI defaults will happily complete a handshake with the
// rendezvous server itself — and since the Hysteria password travels from
// client to server inside that TLS session, that is a credential disclosure,
// not only a redirect.
//
// The boundary, stated positively: the rendezvous server picks which announced
// address a peer talks to and can observe that it happened, but authentication
// of that peer comes entirely from the certificate and the password carried in
// the QUIC handshake. Nothing in this package authenticates a peer, and callers
// must not treat a completed punch as proof of identity.
//
// # Initiator and responder differ on purpose
//
// The initiator (Punch, run by the client) accepts punch packets only from its
// candidate set, including the ports predicted for symmetric NAT peers. This
// costs the client almost nothing: a client behind an address-restricted or
// symmetric NAT can only receive from addresses it has already sent to, so the
// filter mostly re-states what its own NAT enforces, while removing the case
// where a peer with an open path (full-cone NAT, or no NAT at all) hands its
// QUIC socket to whoever spoke first.
//
// The responder (ServerPuncher.Respond, run by the server) defaults to
// accepting any source, because that is the case the filter cannot cover: a
// client behind a symmetric NAT is seen from a port nobody could predict, and
// sometimes from a different IP when the carrier NAT pools addresses. A
// responder that is usually reachable is also the side that loses least by
// being permissive, since it authenticates the peer in the QUIC handshake that
// follows. Callers that know their peers are well behaved can tighten this
// with PunchConfig.SourcePolicy.
//
// # Known gap: metadata confidentiality
//
// PunchMetadata is generated by the initiator and relayed verbatim by the
// rendezvous server, so the obfuscation key is not a secret between the two
// peers. Removing that requires peer identity the rendezvous server does not
// hold — for example a per-peer static public key, with the metadata sealed to
// it — which is the same key material the planned mesh identity layer needs.
// Until then, punch packets defend against passive on-path classifiers, not
// against the rendezvous server.
package realm
