name: "Build release"

on:
  push:
    tags:
      - app/v*.*.*

jobs:
  build:
    uses: ./.github/workflows/build-common.yml

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Get version
        id: get_version
        run: echo "version=$(git describe --tags --always --match 'app/v*' | sed -n 's|app/\([^/-]*\)\(-.*\)\{0,1\}|\1|p')" >> $GITHUB_OUTPUT

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: build-temp-${{ github.sha }}
          path: build

      - name: Upload GitHub
        uses: softprops/action-gh-release@v3
        with:
          files: build/*

